apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: railcloud
spec:
  type: ClusterIP
  selector:
    app: booking-service
  ports:
    - port: 4003
      targetPort: 4003
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: train-service
  namespace: railcloud
spec:
  type: ClusterIP
  selector:
    app: train-service
  ports:
    - port: 4002
      targetPort: 4002
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: railcloud
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - port: 4001
      targetPort: 4001
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: railcloud
spec:
  type: ClusterIP
  selector:
    app: payment-service
  ports:
    - port: 4004
      targetPort: 4004
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: railcloud
spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
    - port: 4005
      targetPort: 4005
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: railcloud
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      name: http
